#!/bin/sh

if [ "x${RUNVALID_PREFIX}" != "x" ];
then
PREFIX=${RUNVALID_PREFIX}
else
PREFIX=../../src
fi


#set -- `getopt g $*`
#set -- `getopt w $*`
#for i
while getopts ":gywt" i
do
    case "$i" in
        g)
            cgdb --args $PREFIX/disksim_base base.parv base.outv ascii $2 0
            grep "ssd Response time average:" base.outv | grep -v "#"
            break;;
        y)    
            cgdb --args $PREFIX/disksim_rosa rosa.parv rosa.outv ascii $2 0
            grep "ssd Response time average:" rosa.outv | grep -v "#"
            break;;

        w)
            $PREFIX/disksim_base base.parv base.outv ascii $2 0  
            grep "ssd Number of pcm read count:" base.outv | grep -v "#"
            grep "ssd Number of nand read count:" base.outv | grep -v "#"
            grep "ssd Number of rd mig:" base.outv | grep -v "#"
            grep "ssd Number of ria mig:" base.outv | grep -v "#"
            grep "ssd Response time average:" base.outv | grep -v "#"
            $PREFIX/disksim_rosa rosa.parv rosa.outv ascii $2 0  
            grep "ssd Number of pcm read count:" rosa.outv | grep -v "#"
            grep "ssd Number of nand read count:" rosa.outv | grep -v "#"
            grep "ssd Number of rd mig:" rosa.outv | grep -v "#"
            grep "ssd Number of ria mig:" rosa.outv | grep -v "#"
            grep "ssd Response time average:" rosa.outv | grep -v "#"
            break;;

        t)
            echo "---Running tests with the synthetic workload generator---"
            echo ""

            echo "Sequential read (250K I/Os): average SSD response time should be around 0.132 ms"
            $PREFIX/disksim ssd-sr250k.parv ssd-sr250k.outv ascii 0 1 
            grep "ssd Response time average:" ssd-sr250k.outv | grep -v "#"
            echo ""

            echo "Sequential write (250K I/Os): average SSD response time should be around 0.310 ms"
            $PREFIX/disksim ssd-sw250k.parv ssd-sw250k.outv ascii 0 1 
            grep "ssd Response time average:" ssd-sw250k.outv | grep -v "#"
            echo ""

            echo "Sequential write (5M I/Os): average SSD response time should be around 0.334 ms"
            $PREFIX/disksim ssd-sw5m.parv ssd-sw5m.outv ascii 0 1 
            grep "ssd Response time average:" ssd-sw5m.outv | grep -v "#"
            echo ""

            echo "Random read (250K I/Os): average SSD response time should be around 0.136 ms"
            $PREFIX/disksim ssd-rr250k.parv ssd-rr250k.outv ascii 0 1 
            grep "ssd Response time average:" ssd-rr250k.outv | grep -v "#"
            echo ""

            echo "Random write (250K I/Os): average SSD response time should be around 0.329 ms"
            $PREFIX/disksim ssd-rw250k.parv ssd-rw250k.outv ascii 0 1 
            grep "ssd Response time average:" ssd-rw250k.outv | grep -v "#"
            echo ""

            echo "Random write (5M I/Os): average SSD response time should be around 0.593 ms"
            $PREFIX/disksim ssd-rw5m.parv ssd-rw5m.outv ascii 0 1 
            grep "ssd Response time average:" ssd-rw5m.outv | grep -v "#"
            echo ""

            echo "---Running tests with the real traces---"
            echo ""

            echo "IOzone: average SSD response time should be around 6.394276 ms"
            $PREFIX/disksim ssd-iozone.parv ssd-iozone.outv ascii ssd-iozone-aligned2-100K.trace 0 
            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
            echo ""

            echo "Postmark: average SSD response time should be around 4.140330 ms"
            $PREFIX/disksim ssd-postmark.parv ssd-postmark.outv ascii ssd-postmark-aligned2.trace 0 
            grep "ssd Response time average:" ssd-postmark.outv | grep -v "#"
            echo ""
            break;;
    esac
done


