#!/bin/bash

if [ "x${RUNVALID_PREFIX}" != "x" ];
then
PREFIX=${RUNVALID_PREFIX}
else
PREFIX=../../src
fi

CVTPATH=~/01_PN_SSD/ssdmodel/testPNSSD/fast_test/spc_trace
#CVTPATH=
#CVTPATH=~/00_svn/users/donghwan/spc_trace
#echo "PCM NAND Hybrid SSD simulation test"
#echo ""

#echo "Making..."
#make clean -s -C ../../
#make -s -C ../../

set -- `getopt g $*`
for i
do
    case "$i"
    in
        -g)
            echo "gdb --args ../../src/disksim ssd-iozone.parv ssd-iozone.outv ascii" $3 "0";
            echo "
            ";
            cgdb --args $PREFIX/disksim ssd-iozone.parv ssd-iozone.outv ascii $3 0;
            break;;
        --)
#            echo $2;
#            $PREFIX/disksim ssd-iozone.parv ssd-iozone.outv ascii $2 0;
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
            for trace in cvt_reCFS cvt_WebSearch1 cvt_WebSearch2 cvt_WebSearch3
            do
                for iter in 1 
                do
                echo "${iter}_${trace}"
#                cgdb --args $PREFIX/disksim ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch${trace}.trace 0
                $PREFIX/disksim_${iter} ssd-iozone.parv ssd-iozone.outv ascii ${trace}.trace 0
                grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
                grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
                grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
                grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
                grep "ssd Number of rd mig:"  ssd-iozone.outv | grep -v "#"
                grep "ssd Number of ria mig:"  ssd-iozone.outv | grep -v "#"
                grep "ssd Number of normal gc:"  ssd-iozone.outv | grep -v "#"
                grep "ssd Number of ria gc:"  ssd-iozone.outv | grep -v "#"
                grep "ssd Number of ria pcm write count:"  ssd-iozone.outv | grep -v "#"
                grep "ssd Number of ria nand write count:"  ssd-iozone.outv | grep -v "#"
                grep "ssd Response time average:"  ssd-iozone.outv | grep -v "#"
                grep "Overall I/O System Response time average:"  ssd-iozone.outv | grep -v "#"
                grep "Overall I/O System Non-Critical Read Response time average:"  ssd-iozone.outv | grep -v "#"
                grep "Overall I/O System Non-Critical Write Response time average:"  ssd-iozone.outv | grep -v "#"
                cp ssd-iozone.outv base_result/${iter}_${trace}.outv
                free && sync && echo 3 > /proc/sys/vm/drop_caches && free
                done
            done
#            echo "50 cvt_WebSearch2"
#            $PREFIX/disksim_50 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch2.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "50 cvt_WebSearch3"
#            $PREFIX/disksim_50 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch3.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "100 cvt_WebSearch1"
#            $PREFIX/disksim_100 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch1.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "100 cvt_WebSearch2"
#            $PREFIX/disksim_100 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch2.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "100 cvt_WebSearch3"
#            $PREFIX/disksim_100 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch3.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#
#            echo "150 cvt_WebSearch1"
#            $PREFIX/disksim_150 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch1.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "150 cvt_WebSearch2"
#            $PREFIX/disksim_150 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch2.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "150 cvt_WebSearch3"
#            $PREFIX/disksim_150 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch3.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#
#            echo "200 cvt_WebSearch1"
#            $PREFIX/disksim_200 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch1.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "200 cvt_WebSearch2"
#            $PREFIX/disksim_200 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch2.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "200 cvt_WebSearch3"
#            $PREFIX/disksim_200 ssd-iozone.parv ssd-iozone.outv ascii cvt_WebSearch3.trace 0
#            grep "ssd Number of pcm read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand read count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria mig:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria gc:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria pcm write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Number of ria nand write count:" ssd-iozone.outv | grep -v "#"
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"

#            echo "cvt_Financial1";
#            $PREFIX/disksim ssd-iozone.parv ssd-iozone.outv ascii cvt_Financial1.trace 0;
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
#            echo "cvt_Financial2";
#            $PREFIX/disksim ssd-iozone.parv ssd-iozone.outv ascii cvt_Financial2.trace 0;
#            grep "ssd Response time average:" ssd-iozone.outv | grep -v "#"
            break;;
     esac
done
